spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wheretogo
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        ddl-auto: update # ğŸ”„ ìŠ¤í‚¤ë§ˆ ìë™ ì—…ë°ì´íŠ¸
        format_sql: true # ğŸ§¹ SQL ì¿¼ë¦¬ í¬ë§·íŒ…
        use_sql_comments: true # ğŸ’¬ SQL ì£¼ì„ í™œì„±í™”
    show-sql: true # ğŸ“ SQL ì¿¼ë¦¬ ì¶œë ¥
