server:
  port: 8081

spring:
  profiles:
    active: local # ğŸ” ê¸°ë³¸ í”„ë¡œíŒŒì¼ ì„¤ì •

  jpa:
    open-in-view: false


#ì„¤ì • ì„¤ëª… ì¶œë ¥ ìœ„ì¹˜ ë¡œê·¸ í¬ë§·
#hibernate.use_sql_comments: true, ì¿¼ë¦¬ ìœ„ì— ë¬´ìŠ¨ ì¼ì„ ìœ„í•´ ì¿¼ë¦¬ë¥¼ ë‚ ë¦¬ëŠ”ì§€ ì£¼ì„ì„ ì¶œë ¥, ë¡œê±° (Logger), Hibernate ê°€ ë§Œë“  ì£¼ì„
#show-sql: true, ì‹¤ì œ ì‹¤í–‰ë˜ëŠ” SQL ì¿¼ë¦¬ë¥¼ ì½˜ì†”ì— ì¶œë ¥, System.out (í‘œì¤€ ì¶œë ¥), SQL ë§Œ ë‚˜ì˜´